#! /bin/zsh
/usr/bin/perl /Applications/hatebgrowl.app/Contents/MacOS/hatena.pl http://shigemk2.hatenablog.com/ | xargs /usr/local/bin/growlnotify -t 'はてブ数' --image /Applications/hatebgrowl.app/Contents/Resources/hatena.tiff

